name: Docker Build and Push
on: [push]  # 每次推送代码时触发自动构建
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # 拉取仓库代码
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .  # 使用当前目录作为构建上下文
          push: true  # 构建后自动推送到Docker Hub
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/icloud-photos-syncer:latest
