name: Build and Push Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/icloud-sync-cn:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/icloud-sync-cn:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
